module.exports.commandes = [
    /* 0  */"Commande inconnue. Tapez **$help** pour avoir le liste des commandes.",
    /* 1  */"\t**$help** \t Affiche la liste de toutes les commandes.",
    /* 2  */"\t**$jouer** \t Créé un profil pour jouer (indispensable).",
    /* 3  */"\t**$banque help** \t Affiche l'aide concernant la banque.",
    /* 4  */"\t**$magasin help** \t Affiche l'aide concernant le magasin.",
    /* 5  */"\t**$métier help** \t Affiche l'aide concernant les métiers.",
    /* 6  */"\t**$inventaire help** \t Affiche l'aide concernant l'inventaire.",
    /* 7  */"\t**$payer help** \t Affiche l'aide sur comment payer quelqu'un.",
    /* 8  */"\t**$entreprise help** \t Affiche l'aide concernant les entreprises.",
    /*      ////////////////////////////////////////////////////////////////////// */
    /* 9  */"\t**$banque compte ouvrir** \t Ouvre un compte en banque à votre nom.",
    /* 10 */"\t**$banque compte cloturer** \t Cloture votre compte en banque et met votre argent dans votre inventaire.",
    /* 11 */"\t**$banque déposer <montant>** \t Dépose le montant d'argent que vous avez sur vous sur votre compte en banque.",
    /* 12 */"\t**$banque retrait <montant>** \t Retire le montant d'argent de votre compte et le place dans votre inventaire.",
    /* 13 */"\t**$banque verser <pseudo joueur|id> <montant>** \t Verse un certaint montant d'argent à un joueur depuis votre compte.",
    /* 14 */"\t**$magasin stock** \t Affiche les stocks disponibles dans le magasin ainsi que le prix des objets.",
    /* 15 */"\t**$magasin acheter <nom ojet|numéro> <quantité>** Achête les objets dans le magasin et les met dans votre inventaire.",
    /* 16 */"\t**$métier liste** \t Affiche la liste de tous les métiers et salaires.",
    /* 17 */"\t**$métier postuler <nom métier>** \t Vous affecte un nouveau métier.",
    /* 18 */"\t**$métier quitter** \t Vous quittez votre métier et vous retrouvez sans emploi.",
    /* 19 */"\t**$inventaire ouvrir** \t Ouvre votre inventaire et vous montre son contenu.",
    /* 20 */"\t**$inventaire jeter <nom objet|numéro>** Vous vous débarassez de l'bjet en question.",
    /* 21 */"\t**$payer <pseudo joueur|id> <montant>** \t Paye la somme spécifiée au joueur désigné.",
    /* 22 */"\t**$entreprise liste** \t Affiche la liste de toutes les entreprises",
    /* 23 */"\t**$entreprise postuler <nom entreprise>** \t Vous demandez pour rejoindre l'entreprise indiquée.",
    /* 24 */"\t**$entreprise virer <pseudo joueur|id> <motif>** \t Vire la personne pour un certain motif.\n\t(La personne virée se verra payer l'équivalent de 3 mois de salaire comme indemnités.",
    /* 25 */"\t**$entreprise employés <nom entreprise>** \t Affiche la liste des employés de l'entreprise indiquée."
];